In [4]:
import numpy as np
from numpy import linalg as LA

In [29]:
row = int(input("Enter the number of rows of the matrix: "))
col = int(input("Enter the number of column of the matrix: ")) 

matrix = []
for x in range(0, row):
	list_x = []
	matrix.append(list_x)
	for y in range(0, col):
		list_x.append(int(input("Enter the element of row " + str(x+1) +" of the Matrix:")))
		
print("M:",matrix)


M: [[1, 2, 3], [4, 5, 6]]


In [66]:
matrix_trans = np.transpose(matrix)
A_AT = np.matmul(matrix, matrix_trans)
print(A_AT)

[[14 32]
 [32 77]]


In [67]:
A_ATeigval, A_ATeigvec = LA.eig(A_AT)
print(A_ATeigval)
print(A_ATeigvec)

[ 0.59732747 90.40267253]
[[-0.92236578 -0.3863177 ]
 [ 0.3863177  -0.92236578]]


In [68]:
AT_A = np.matmul(matrix_trans, matrix)
print(AT_A)

[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [69]:
AT_Aeigval, AT_Aeigvec = LA.eig(AT_A)
print(AT_Aeigval)
print(AT_Aeigvec)

[ 9.04026725e+01  5.97327474e-01 -4.04484173e-15]
[[-0.42866713 -0.80596391  0.40824829]
 [-0.56630692 -0.11238241 -0.81649658]
 [-0.7039467   0.58119908  0.40824829]]


In [70]:
lambda_mat= []
for i in range(len(A_ATeigval)):
    list = []
    lambda_mat.append(list)
    for y in range(0, col):
        if(y == i):
            list.append(np.sqrt(A_ATeigval[i]))
        else:
            list.append(0)

print(lambda_mat)

[[0.7728696356734833, 0, 0], [0, 9.508032000695724, 0]]


In [71]:
U = A_ATeigvec
V_T = np.transpose(AT_Aeigvec)

print(U)
print(V_T)

[[-0.92236578 -0.3863177 ]
 [ 0.3863177  -0.92236578]]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [-0.80596391 -0.11238241  0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [72]:
Intermediate_A= np.matmul(U, lambda_mat)

A = np.matmul(Intermediate_A, V_T)
print(A)

[[ 3.26598632  0.81649658 -1.63299316]
 [ 6.94022094  0.81649658 -5.30722778]]
